baseURL = "https://abogsnes.com"
languageCode = "en-us"
title = "Anders Bogsnes"
theme = ["hugo-theme-codex", "reveal-hugo"]
enableEmoji = true


# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"

[[menu.main]]
 identifier = "presentations"
 name = "presentations"
 title = "Presentations"
 url = "/presentations/"

[params]
github = "https://github.com/andersbogsnes"
twitter = "https://twitter.com/andersbogsnes"
linkedin = "https://www.linkedin.com/in/andersbogsnes/"

iconOrder = ["GitHub", "Linkedin", "Twitter"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediatype = "text/html"
isHTML = true

[params.reveal_hugo]
transition_speed = 'fast'
theme="serif"
width=1024
height=768
